const products = [
  {
    id: 1,
    name: "Product A",
    price: 29.99,
    image: "https://source.unsplash.com/random/800x600/?product",
    inStock: true,
    fastDelivery: true,
    rating: 4.5,
    category: "Electronics",
  },
  {
    id: 2,
    name: "Product B",
    price: 49.99,
    image: "https://source.unsplash.com/random/800x600/?gadget",
    inStock: false,
    fastDelivery: false,
    rating: 3.2,
    category: "Home & Kitchen",
  },
  {
    id: 3,
    name: "Product C",
    price: 19.99,
    image: "https://source.unsplash.com/random/800x600/?clothing",
    inStock: true,
    fastDelivery: true,
    rating: 4.8,
    category: "Fashion",
  },
  {
    id: 4,
    name: "Product D",
    price: 99.99,
    image: "https://source.unsplash.com/random/800x600/?furniture",
    inStock: true,
    fastDelivery: false,
    rating: 4.0,
    category: "Home & Decor",
  },
  {
    id: 5,
    name: "Product E",
    price: 39.99,
    image: "https://source.unsplash.com/random/800x600/?electronics",
    inStock: true,
    fastDelivery: true,
    rating: 4.2,
    category: "Electronics",
  },
  {
    id: 6,
    name: "Product F",
    price: 79.99,
    image: "https://source.unsplash.com/random/800x600/?home",
    inStock: true,
    fastDelivery: true,
    rating: 4.6,
    category: "Home & Decor",
  },
  {
    id: 7,
    name: "Product G",
    price: 59.99,
    image: "https://source.unsplash.com/random/800x600/?fashion",
    inStock: true,
    fastDelivery: false,
    rating: 3.9,
    category: "Fashion",
  },
  {
    id: 8,
    name: "Product H",
    price: 24.99,
    image: "https://source.unsplash.com/random/800x600/?kitchen",
    inStock: true,
    fastDelivery: true,
    rating: 4.1,
    category: "Home & Kitchen",
  },
  {
    id: 9,
    name: "Product I",
    price: 34.99,
    image: "https://source.unsplash.com/random/800x600/?beauty",
    inStock: true,
    fastDelivery: true,
    rating: 4.7,
    category: "Beauty",
  },
  {
    id: 10,
    name: "Product J",
    price: 14.99,
    image: "https://source.unsplash.com/random/800x600/?shoes",
    inStock: true,
    fastDelivery: true,
    rating: 4.4,
    category: "Fashion",
  },

  {
    id: 11,
    name: "Product K",
    price: 89.99,
    image: "https://source.unsplash.com/random/800x600/?tech",
    inStock: false,
    fastDelivery: true,
    rating: 3.5,
    category: "Electronics",
  },
  {
    id: 12,
    name: "Product L",
    price: 69.99,
    image: "https://source.unsplash.com/random/800x600/?furniture",
    inStock: true,
    fastDelivery: true,
    rating: 4.2,
    category: "Home & Decor",
  },
  {
    id: 13,
    name: "Product M",
    price: 19.99,
    image: "https://source.unsplash.com/random/800x600/?clothing",
    inStock: true,
    fastDelivery: false,
    rating: 3.8,
    category: "Fashion",
  },
  {
    id: 14,
    name: "Product N",
    price: 49.99,
    image: "https://source.unsplash.com/random/800x600/?gadget",
    inStock: true,
    fastDelivery: true,
    rating: 4.7,
    category: "Electronics",
  },
  {
    id: 15,
    name: "Product O",
    price: 39.99,
    image: "https://source.unsplash.com/random/800x600/?beauty",
    inStock: false,
    fastDelivery: false,
    rating: 3.2,
    category: "Beauty",
  },
  {
    id: 16,
    name: "Product P",
    price: 29.99,
    image: "https://source.unsplash.com/random/800x600/?kitchen",
    inStock: true,
    fastDelivery: true,
    rating: 4.6,
    category: "Home & Kitchen",
  },
  {
    id: 17,
    name: "Product Q",
    price: 19.99,
    image: "https://source.unsplash.com/random/800x600/?fashion",
    inStock: true,
    fastDelivery: true,
    rating: 4.3,
    category: "Fashion",
  },
  {
    id: 18,
    name: "Product R",
    price: 99.99,
    image: "https://source.unsplash.com/random/800x600/?tech",
    inStock: true,
    fastDelivery: true,
    rating: 4.9,
    category: "Electronics",
  },
  {
    id: 19,
    name: "Product S",
    price: 49.99,
    image: "https://source.unsplash.com/random/800x600/?home",
    inStock: true,
    fastDelivery: false,
    rating: 3.7,
    category: "Home & Decor",
  },
  {
    id: 20,
    name: "Product T",
    price: 14.99,
    image: "https://source.unsplash.com/random/800x600/?shoes",
    inStock: true,
    fastDelivery: true,
    rating: 4.5,
    category: "Fashion",
  },
];

export default products;
